// DB IDL
#ifndef _DB_IDL_
#define _DB_IDL_

module JobService {
		
		exception HandlerNotRegistered {};

		interface JobGeoDetails {
				enum CurrencyEnum {kzt, usd, rub, gbp};
				enum CountryEnum {kazakhstan, russia, great_britain, usa};
		};
		
		struct job {
				string title;
				unsigned long salary;
				JobGeoDetails::CurrencyEnum currency;
				JobGeoDetails::CountryEnum country;
				sequence <string<146>, 4> reqments;
				sequence <string<146>, 4> job_details;
		};

		typedef job JobEntitiy;

		enum Status {success, fail};

		interface JobHandler {
				attribute string<20> hname;
		};


		interface Submitable : JobHandler {
				Status submit_job(in JobEntitiy JobCtx)
						raises(HandlerNotRegistered);
		};

		interface Validateable : JobHandler {
				Status validate_job(inout JobEntitiy JobCtx)
						raises(HandlerNotRegistered);
		};

		interface Processable : JobHandler {
				Status process_job(inout JobEntitiy JobCtx)
						raises(HandlerNotRegistered);
		};

		interface Storeable : JobHandler {
				Status store_job(in JobEntitiy JobCtx)
						raises(HandlerNotRegistered);
		};
};

#endif